# Problem 1 

In [5]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 5 elemanlı bir numpy array oluşturun
a=np.array([23,18,48,32,93])
# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
a=np.sort(a)
print(a)







[18 23 32 48 93]


# Problem 2

In [78]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
import numpy as np
a=np.array([10,15,30,45,60])
print("1-",a)



# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
a=np.arange(5,15)
print("2-",a)




# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
a=np.arange(50,100,5)
print("3-", a)



# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
a = np.zeros(10)
print("4-",a)





# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
a=np.ones(10)
print("5-",a)




# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
a = np.linspace(0, 100, 5)
print("6-",a)





# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
a=np.random.randint(10,30,5)
print("7-",a)





# 8- [-1 ile 1] arasında 10 adet sayı üretin.
a=np.random.normal(-1,1,10)
print("8-",a)





# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
a=np.array([[12,48,33,26,19],
           [35,42,16,25,18],
           [23,37,49,11,27]])
print("9-",a)

    #Rastgele matris oluşturursak;
b=np.random.randint(10,50, size=(3,5))
print("9-Rastgele matris oluşturulduğunda:",b)






# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
a=np.array([[12,48,33,26,19],
           [35,42,16,25,18],
           [23,37,49,11,27]])
satır=np.sum(a, axis=0)
sütun=np.sum(a, axis=1)
satırtoplam = np.sum(satır)
sütuntoplam = np.sum(sütun)
print("10-Satır toplamları:",satırtoplam)
print("Sütun toplamları:",sütuntoplam)


    #Rastgele matris oluşturursak;
b=np.random.randint(10,50, size=(3,5))
satır=np.sum(b, axis=0)
sütun=np.sum(b, axis=1)
satırtoplam = np.sum(satır)
sütuntoplam = np.sum(sütun)
print("10-Rastgele matris oluşturulduğunda: Satır toplamları:",satırtoplam)
print("Sütun toplamları:",sütuntoplam)







# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
a=np.array([[12,48,33,26,19],
           [35,42,16,25,18],
           [23,37,49,11,27]])
print("11-")
print("matrisin en büyük değeri:",np.max(a))
print("Matrisin en küçük değeri:",np.min(a))
print("Matrisin ortalaması:",np.average(a))


    #Rastgele matris oluşturursak;
b=np.random.randint(10,50, size=(3,5))
print("11-Rastgele matris oluşturulduğunda:")
print("matrisin en büyük değeri:",np.max(b))
print("Matrisin en küçük değeri:",np.min(b))
print("Matrisin ortalaması:",np.average(b))





# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
a=np.array([[12,48,33,26,19],
           [35,42,16,25,18],
           [23,37,49,11,27]])
b=np.max(a)
print("12-",np.where(b))


    #Rastgele matris oluşturursak;
b=np.random.randint(10,50, size=(3,5))
c=np.max(b)
print("12-Rastgele matris oluşturulduğunda:",np.where(c))

# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
a=np.arange(10,20)
print("13-",a[:3])

  




# 14- Üretilen dizinin elemanlarını tersten yazdırın.
a=np.arange(10,20)
print("14",a[::-1])


# 15- Üretilen matrisin ilk satırını seçiniz.
a=np.array([[12,48,33,26,19],
           [35,42,16,25,18],
           [23,37,49,11,27]])
print("15-",a[0])

 #Rastgele matris oluşturursak;
b=np.random.randint(10,50, size=(3,5))
print("15-Rastgele matris oluşturulduğunda:",b[0])






# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
a=np.array([[12,48,33,26,19],
           [35,42,16,25,18],
           [23,37,49,11,27]])
print("16-",a[2,3])

    #Rastgele matris oluşturursak;
b=np.random.randint(10,50, size=(3,5))
print("16-Rastgele matris oluşturulduğunda:",b[2,3])







# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
a=np.array([[12,48,33,26,19],
           [35,42,16,25,18],
           [23,37,49,11,27]])
print("17-",a[:,0])


    #Rastgele matris oluşturursak;
b=np.random.randint(10,50, size=(3,5))
print("17-Rastgele matris oluşturulduğunda:",b[:,0])






# 18- Üretilen matrisin her bir elemanının karesini alınız.
a=np.array([[12,48,33,26,19],
           [35,42,16,25,18],
           [23,37,49,11,27]])
x=np.square(a)
print("18-",x)

    #Rastgele matris oluşturursak;
b=np.random.randint(10,50, size=(3,5))
print("18-Rastgele matris oluşturulduğunda:",np.square(b))







# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.

#Rastgele liste oluşturduğumuzda...

a=np.random.randint(-50,50, size=(3,5))
liste=[]
for satır in a:
    for i in satır:
        if i>0 and i%2==0:
            liste.append(i)
print("19-",liste)
        

1- [10 15 30 45 60]
2- [ 5  6  7  8  9 10 11 12 13 14]
3- [50 55 60 65 70 75 80 85 90 95]
4- [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
5- [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
6- [  0.  25.  50.  75. 100.]
7- [25 16 20 22 11]
8- [-1.2612768  -0.40679678 -0.29700792 -0.65965911 -0.33812687  0.24223869
 -1.57709215 -0.96628612 -0.95585858 -0.30211192]
9- [[12 48 33 26 19]
 [35 42 16 25 18]
 [23 37 49 11 27]]
9-Rastgele matris oluşturulduğunda: [[47 30 23 16 34]
 [16 19 12 24 29]
 [28 41 25 16 43]]
10-Satır toplamları: 421
Sütun toplamları: 421
10-Rastgele matris oluşturulduğunda: Satır toplamları: 514
Sütun toplamları: 514
11-
matrisin en büyük değeri: 49
Matrisin en küçük değeri: 11
Matrisin ortalaması: 28.066666666666666
11-Rastgele matris oluşturulduğunda:
matrisin en büyük değeri: 49
Matrisin en küçük değeri: 12
Matrisin ortalaması: 30.266666666666666
12- (array([0], dtype=int64),)
12-Rastgele matris oluşturulduğunda: (array([0], dtype=int64),)
13- [10 11 12]
14 [19 18 17 16 15 14 13 12 11 10]
15- [